mtd/nand: Fix build error since NAND feature is disabled
drivers/mtd/nand/nand_base.c:2863:12:
error: ‘nand_flash_detect_onfi’ defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors

Change-Id: I66511666e9dc561ae8adc06d73aa21b3856d3a37
Signed-off-by: Dongjin Kim <tobetter@gmail.com>